### ISSUE TITLE
How to use the multi touch in Python?

### ISSUE THREAD

**Issue by neoxharsh** [pimoroni/hyperpixel#13]
I want to grab multi touches using python, any suggestions?

**Comment by Gadgetoid** [comment]
You can use: https://github.com/pimoroni/python-multitouch

If you change this line: https://github.com/pimoroni/python-multitouch/blob/master/library/ft5406.py#L115

To "Touchscreen"

Don't expect much from the second touch point, due to the size of the green it's not terribly accurate. I've been working on a replacement touch driver to make that, and other things, better which you might see better results from: https://gist.github.com/Gadgetoid/64e57db4a22e4cd585ad35c6be2c7682

It's still a W.I.P. though!
